export enum USER_REGISTER {
  DOCUMENT = 'USER_REGISTER_DOCUMENT',
  EMAIL_MOBILE = 'USER_REGISTER_EMAIL_MOBILE',
  NAME_BIRTHDATE = 'USER_REGISTER_NAME_BIRTHDATE',
  ADDRESS = 'USER_REGISTER_ADDRESS',
  PASSWORD = 'USER_REGISTER_PASSWORD',
  SELFIE = 'USER_REGISTER_SELFIE',
  DOCUMENT_FRONT_IMAGE = 'USER_REGISTER_DOCUMENT_FRONT_IMAGE',
  DOCUMENT_BACK_IMAGE = 'USER_REGISTER_DOCUMENT_BACK_IMAGE',
  PUSH_NOTIFICATION_TOKEN = 'USER_REGISTER_NOTIFICATION_TOKEN',
}
