export enum PROFILE {
  AREA = 'PIX_AREA_VIEW',
  PROFILE = 'PROFILE_VIEW',
  DATA = 'DATA_SCREEN',
  CONFIG = 'CONFIG_STACK',
  SAFETY = 'SAFETY_STACK',
  HELP = 'HELP_STACK',
  DISABLE = 'DISABLE_STACK',
}
