export enum PUBLIC {
  DEV = 'DEV_VIEW',
  STORYBOOK = 'STORYBOOK',
  VERIFY_EMAIL = 'VERIFY_EMAIL',
  HOME = 'HOME_VIEW',
  LOGIN = 'LOGIN_VIEW',
  EMAILNAME = 'EMAILNAME_VIEW',
  PASSWORD = 'PASSWORD_VIEW',
  PLACEHOLDER = 'PLACEHOLDER_VIEW',
}
