export enum PUBLIC {
  DEV = 'DEV_VIEW',
  STORYBOOK = 'STORYBOOK',

  HOME = 'HOME_VIEW',
  LOGIN = 'LOGIN_VIEW',
  BIRTHDATE = 'BIRTHDATE_VIEW',
  EMAILNAME = 'EMAILNAME_VIEW',
  EMAIL = 'EMAIL_VIEW',
  ADDRESS = 'ADDRESS_VIEW',
  PASSWORD = 'PASSWORD_VIEW',
  SELFIEGUIDE = 'SELFIEGUIDE_VIEW',
  SELFIE = 'SELFIE_VIEW',
  DOCUMENT = 'DOCUMENT_VIEW',
  JURIDICAL_PERSON = 'JURIDICAL_PERSON_STACK',
  RESIDENCE_PROOF = 'RESIDENCE_PROOF_VIEW',
  AKNOWLEDGEMENT = 'AKNOWLEDGEMENT_VIEW',
  FINANCE_PASSWORD = 'CREATE_FINANCE_PASSWORD_VIEW'
}
