export enum COMPANY_REGISTER {
  NAME = 'COMPANY_REGISTER_COMPANY_NAME',
  DOCUMENT = 'COMPANY_REGISTER_DOCUMENT',
  EMAIL = 'COMPANY_REGISTER_EMAIL',
  PHONE = 'COMPANY_REGISTER_PHONE',
  SYNC = 'COMPANY_REGISTER_SYNC',
}
