export enum RECHARGE {
  GET_OPERATORS = 'GET_RECHARGE_OPERATORS',
  SELECTED_OPERATOR = 'GET_RECHARGE_SELECTED_OPERATOR',
  GET_PRODUCTS = 'GET_RECHARGE_PRODUCTS',
  SELECTED_PRODUCTS = 'GET_RECHARGE_SELECTED_PRODUCTS',
  GET_OPERATOR_LOADING = 'GET_OPERATOR_LOADING',
}
