export enum DASHBOARD {
  DASHBOARD = 'DASHBOARD_VIEW',
  WALLET = 'WALLET_STACK',
  TRANSACTIONS = 'TRANSACTIONS_STACK',
  STATEMENT = 'STATEMENT_VIEW',
  PROFILE = 'PROFILE_STACK',
  PIX = 'PIX_STACK'
}
